databases:
  - name: technova-db
    databaseName: technova
    user: technova_app
    plan: free

services:
  - type: web
    name: technova-solutions
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TECHNOVA_DB_HOST
        fromDatabase:
          name: technova-db
          property: host
      - key: TECHNOVA_DB_USER
        fromDatabase:
          name: technova-db
          property: user
      - key: TECHNOVA_DB_PASSWORD
        fromDatabase:
          name: technova-db
          property: password
      - key: TECHNOVA_DB_NAME
        fromDatabase:
          name: technova-db
          property: database
      - key: TECHNOVA_DB_PORT
        fromDatabase:
          name: technova-db
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: technova-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: FLASK_ENV
        value: production
